# Generated by Django 3.0.8 on 2020-07-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('empid', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
    ]
